In [1]:
import cv2
import numpy as np
import face_recognition
import os
from datetime import datetime

In [2]:
path = 'ImagesAttendance'
images = []
classNames = []
myList = os.listdir(path)
print(myList)

['Aastha.jpg', 'MS Dhoni.jpg', 'Neeraj Chopra.jpg', 'PV Sindhu.jpg', 'Saina Nehwal.jpg']


In [3]:
for cls in myList:
    curImg = cv2.imread(f'{path}/{cls}')
    images.append(curImg)
    classNames.append(os.path.splitext(cls)[0])
print(classNames)

['Aastha', 'MS Dhoni', 'Neeraj Chopra', 'PV Sindhu', 'Saina Nehwal']


In [4]:
def findEncodings(images):
    encodeList = []
    for img in images:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)        # converting each image to RGB
        encode = face_recognition.face_encodings(img)[0]
        encodeList.append(encode)
    return encodeList        

In [5]:
def mark_attendance(name):
    with open('AttendanceRegister.csv','r+') as f:
        myDataList = f.readlines()
        nameList = []
        #print(myDataList)
        for line in myDataList:
            entry = line.split(',')
            nameList.append(entry[0])
        if name not in nameList:
            now = datetime.now()
            dtString = now.strftime('%H:%M:%S')
            f.writelines(f'\n{name},{dtString}')

In [6]:
encodeListKnown = findEncodings(images)
print(len(encodeListKnown))

5


In [7]:
cap = cv2.VideoCapture(0)

In [ ]:
while True:
    success, img = cap.read()
    imgS = cv2.resize(img,(0,0),None,0.25,0.25)     # reducing the size of image to speed up the process
    imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB)    # converting it to RGB
    facesCurrFrame = face_recognition.face_locations(imgS)    # finding location of face in webcam
    encodeCurFrame = face_recognition.face_encodings(imgS, facesCurrFrame)
    
    for encodeFace, faceLoc in zip(encodeCurFrame, facesCurrFrame):
        matches = face_recognition.compare_faces(encodeListKnown, encodeFace)
        faceDis = face_recognition.face_distance(encodeListKnown, encodeFace)
        print(faceDis)
        matchIndex = np.argmin(faceDis)
        
        if matches[matchIndex]:
            name = classNames[matchIndex].upper()
            print(name)
            y1,x2,y2,x1 = faceLoc
            y1,x2,y2,x1 = y1*4,x2*4,y2*4,x1*4
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
            cv2.rectangle(img,(x1,y2-35),(x2,y2),(0,255,0),cv2.FILLED)
            cv2.putText(img,name,(x1+6,y2-6),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,255),2)
            mark_attendance(name)
            
    cv2.imshow("Webcam",img)    #showing original image
    cv2.waitKey(1)

[0.52862585 0.75738637 0.82273499 0.57969435 0.67200509]
AASTHA
[0.5466647  0.74921482 0.84477695 0.63100463 0.68624106]
AASTHA
[0.53024668 0.74902274 0.87005457 0.56827851 0.70427197]
AASTHA
[0.57148983 0.73010255 0.8351522  0.54769489 0.69809144]
PV SINDHU
[0.53370489 0.69646392 0.82809832 0.58724898 0.68624143]
AASTHA
[0.56670038 0.77626727 0.8652248  0.55360633 0.6981537 ]
PV SINDHU
[0.58966139 0.80199466 0.87584843 0.55692271 0.67412188]
PV SINDHU
[0.54429045 0.81896924 0.87100685 0.57001729 0.70324224]
AASTHA
[0.562286   0.72223171 0.86909504 0.60994536 0.74562832]
AASTHA
[0.52505463 0.6696011  0.83746607 0.54684519 0.68788336]
AASTHA
[0.52481115 0.72278622 0.85935358 0.54407638 0.66580647]
AASTHA
[0.54840087 0.71827018 0.85664081 0.56378869 0.69984748]
AASTHA
[0.52671294 0.76483821 0.88420119 0.57147109 0.7316765 ]
AASTHA
[0.56066569 0.68890416 0.81204225 0.60705868 0.73858041]
AASTHA
[0.55940469 0.73558304 0.83957036 0.59511792 0.70695603]
AASTHA
[0.51173589 0.7292194  0.885398