In [23]:
import cv2
import numpy as np
import face_recognition

In [24]:
imgPV = face_recognition.load_image_file('images/PV Sindhu.jpg')
imgPV = cv2.cvtColor(imgPV,cv2.COLOR_BGR2RGB)

In [25]:
imgTest = face_recognition.load_image_file('images/PV Test.jpg')
imgTest = cv2.cvtColor(imgTest,cv2.COLOR_BGR2RGB)

In [26]:
imgSaina = face_recognition.load_image_file('images/Saina Nehwal.jpg')
imgSaina = cv2.cvtColor(imgSaina,cv2.COLOR_BGR2RGB)

In [27]:
faceLoc = face_recognition.face_locations(imgPV)[0]                #detecting the face
encodePV = face_recognition.face_encodings(imgPV)[0]             #finding encoding
# faceLoc give four coordinates of the face detected  - top right bottom left

In [28]:
faceLoc = face_recognition.face_locations(imgTest)[0]                #detecting the face
encodeTest = face_recognition.face_encodings(imgTest)[0]             #finding encoding
cv2.rectangle(imgTest,(faceLoc[3],faceLoc[0]),(faceLoc[1],faceLoc[2]),(255,0,255),2)

array([[[18, 17, 13],
        [18, 17, 13],
        [18, 17, 13],
        ...,
        [26, 10, 88],
        [26, 10, 88],
        [26, 10, 88]],

       [[17, 16, 12],
        [17, 16, 12],
        [17, 16, 12],
        ...,
        [26, 10, 88],
        [26, 10, 88],
        [26, 10, 88]],

       [[15, 14, 10],
        [15, 14, 10],
        [15, 13, 12],
        ...,
        [26, 10, 88],
        [26, 10, 88],
        [26, 10, 88]],

       ...,

       [[25, 16, 56],
        [25, 16, 56],
        [25, 16, 56],
        ...,
        [28,  9, 94],
        [28,  9, 94],
        [28,  9, 94]],

       [[25, 16, 56],
        [25, 16, 56],
        [25, 16, 56],
        ...,
        [28,  9, 94],
        [28,  9, 94],
        [28,  9, 94]],

       [[25, 16, 56],
        [25, 16, 56],
        [25, 16, 56],
        ...,
        [28,  9, 94],
        [28,  9, 94],
        [28,  9, 94]]], dtype=uint8)

In [29]:
cv2.rectangle(imgPV,(faceLoc[3],faceLoc[0]),(faceLoc[1],faceLoc[2]),(255,0,255),2)          
# drawing purple rectangle over the face detected

array([[[ 53,  79,  65],
        [ 53,  79,  65],
        [ 53,  79,  65],
        ...,
        [ 57,  81,  69],
        [ 55,  79,  67],
        [ 54,  78,  66]],

       [[ 53,  79,  65],
        [ 53,  79,  65],
        [ 53,  79,  65],
        ...,
        [ 57,  81,  69],
        [ 55,  79,  67],
        [ 54,  78,  66]],

       [[ 52,  78,  64],
        [ 53,  79,  65],
        [ 53,  79,  65],
        ...,
        [ 57,  81,  69],
        [ 55,  79,  67],
        [ 54,  78,  66]],

       ...,

       [[214, 123,  38],
        [214, 123,  38],
        [214, 123,  38],
        ...,
        [245, 219, 212],
        [235, 207, 196],
        [223, 194, 179]],

       [[214, 123,  38],
        [214, 123,  38],
        [214, 123,  38],
        ...,
        [234, 208, 201],
        [222, 194, 183],
        [209, 180, 165]],

       [[214, 123,  38],
        [214, 123,  38],
        [214, 123,  38],
        ...,
        [225, 199, 192],
        [211, 183, 172],
        [197, 168, 153]]

In [31]:
faceLoc = face_recognition.face_locations(imgSaina)[0]                #detecting the face
encodeSaina = face_recognition.face_encodings(imgSaina)[0]             #finding encoding
cv2.rectangle(imgSaina,(faceLoc[3],faceLoc[0]),(faceLoc[1],faceLoc[2]),(255,0,255),2)

array([[[213, 149, 145],
        [214, 150, 146],
        [214, 150, 146],
        ...,
        [130,  76,  83],
        [130,  76,  83],
        [130,  76,  83]],

       [[214, 150, 146],
        [214, 150, 146],
        [214, 150, 146],
        ...,
        [130,  76,  83],
        [130,  76,  83],
        [130,  76,  83]],

       [[214, 150, 146],
        [214, 150, 146],
        [215, 151, 147],
        ...,
        [131,  77,  84],
        [131,  77,  84],
        [131,  77,  84]],

       ...,

       [[223, 132, 127],
        [223, 132, 127],
        [221, 133, 126],
        ...,
        [208, 175, 179],
        [191, 158, 162],
        [179, 146, 150]],

       [[229, 137, 132],
        [228, 136, 131],
        [227, 136, 129],
        ...,
        [211, 176, 180],
        [194, 159, 163],
        [181, 146, 150]],

       [[237, 140, 136],
        [233, 139, 134],
        [231, 137, 131],
        ...,
        [211, 176, 180],
        [194, 159, 163],
        [182, 147, 151]]

In [33]:
results = face_recognition.compare_faces([encodePV],encodeTest)
faceDis = face_recognition.face_distance([encodePV],encodeTest)
print(results, faceDis)
cv2.putText(imgPV,f'{results} {round(faceDis[0],2)}',(10,10),cv2.FONT_HERSHEY_PLAIN,1,(0,255,255),1)

[True] [0.46371489]


array([[[ 53,  79,  65],
        [ 53,  79,  65],
        [ 53,  79,  65],
        ...,
        [ 57,  81,  69],
        [ 55,  79,  67],
        [ 54,  78,  66]],

       [[ 53,  79,  65],
        [ 53,  79,  65],
        [ 53,  79,  65],
        ...,
        [ 57,  81,  69],
        [ 55,  79,  67],
        [ 54,  78,  66]],

       [[ 52,  78,  64],
        [ 53,  79,  65],
        [ 53,  79,  65],
        ...,
        [ 57,  81,  69],
        [ 55,  79,  67],
        [ 54,  78,  66]],

       ...,

       [[214, 123,  38],
        [214, 123,  38],
        [214, 123,  38],
        ...,
        [245, 219, 212],
        [235, 207, 196],
        [223, 194, 179]],

       [[214, 123,  38],
        [214, 123,  38],
        [214, 123,  38],
        ...,
        [234, 208, 201],
        [222, 194, 183],
        [209, 180, 165]],

       [[214, 123,  38],
        [214, 123,  38],
        [214, 123,  38],
        ...,
        [225, 199, 192],
        [211, 183, 172],
        [197, 168, 153]]

In [34]:
result2 = face_recognition.compare_faces([encodeSaina],encodeTest)
faceDis2 = face_recognition.face_distance([encodeSaina],encodeTest)
print(results, faceDis2)
cv2.putText(imgSaina,f'{result2} {round(faceDis2[0],2)}',(10,10),cv2.FONT_HERSHEY_PLAIN,1,(0,255,255),1)

[True] [0.70515041]


array([[[213, 149, 145],
        [214, 150, 146],
        [214, 150, 146],
        ...,
        [130,  76,  83],
        [130,  76,  83],
        [130,  76,  83]],

       [[214, 150, 146],
        [214, 150, 146],
        [214, 150, 146],
        ...,
        [130,  76,  83],
        [130,  76,  83],
        [130,  76,  83]],

       [[214, 150, 146],
        [214, 150, 146],
        [215, 151, 147],
        ...,
        [131,  77,  84],
        [131,  77,  84],
        [131,  77,  84]],

       ...,

       [[223, 132, 127],
        [223, 132, 127],
        [221, 133, 126],
        ...,
        [208, 175, 179],
        [191, 158, 162],
        [179, 146, 150]],

       [[229, 137, 132],
        [228, 136, 131],
        [227, 136, 129],
        ...,
        [211, 176, 180],
        [194, 159, 163],
        [181, 146, 150]],

       [[237, 140, 136],
        [233, 139, 134],
        [231, 137, 131],
        ...,
        [211, 176, 180],
        [194, 159, 163],
        [182, 147, 151]]

In [35]:
cv2.imshow("PV Sindhu", imgPV)
cv2.imshow("PV Test", imgTest)
cv2.imshow("Saina Nehwal", imgSaina)
cv2.waitKey(0)

-1